# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for moment
	pod 'TensorFlow-experimental'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

end
